<template>
  <div class="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center z-50">
    <div
      class="main-card max-w-[85vw] max-h-[85vh] lg:max-w-[90vw] lg:max-h-[90vh] px-6 py-4 flex flex-col"
    >
      <div class="flex justify-center mb-4">
        <SmartPackLogoIcon class="w-28 h-20 lg:w-32 lg:h-24" aria-label="SmartPack Logo" />
      </div>

      <div class="h-full overflow-y-auto card-base mb-4 px-2 text-sm secondary-text">
        <h2 class="text-lg main-heading">SMARTPACK TERMS AND CONDITIONS</h2>

        <p class="mt-2"><strong>Effective Date:</strong> 09/16/2026</p>
        <p class="mt-2"><strong>Version:</strong> 1.0</p>

        <section v-for="section in sections" :key="section.title" class="mt-4">
          <h3 class="font-semibold">{{ section.title }}</h3>

          <p v-for="paragraph in section.paragraphs" :key="paragraph" class="mt-1">
            {{ paragraph }}
          </p>
        </section>

        <div class="mt-4">
          <h3 class="font-semibold">8. CONTACT</h3>

          <p>
            If you have any questions regarding these Terms and Conditions, please contact us
            through the support channels provided by SmartPack.
          </p>

          <p class="mt-2">
            <strong>End of Terms and Conditions</strong>
          </p>
        </div>
      </div>

      <div class="grid grid-cols-2 items-center gap-4 secondary-text">
        <button
          type="button"
          class="form-submit-secondary px-2 py-2 text-xs lg:text-base lg:!max-w-28"
          @click="cancelAgreement"
        >
          Cancel
        </button>

        <button
          type="button"
          class="form-submit px-2 py-2 text-xs lg:text-base lg:!max-w-40 lg:justify-self-end"
          @click="confirmAgreement"
        >
          Accept terms
        </button>
      </div>
    </div>
  </div>
</template>

<script lang="ts">
import { defineComponent } from 'vue'

import SmartPackLogoIcon from '@/components/Icons/SmartPackLogo.vue'

type Section = {
  title: string
  paragraphs: string[]
}

/**
 * Modal that displays the SmartPack terms and conditions
 * and emits `confirmed` when the user selects an action.
 */
export default defineComponent({
  name: 'TermsAgreement',

  components: {
    SmartPackLogoIcon,
  },

  emits: ['confirmed'],

  setup(_, { emit }) {
    const sections: Section[] = [
      {
        title: '1. SERVICES OVERVIEW',
        paragraphs: [
          '1.1 SmartPack provides smart schoolbag technology and software services designed to monitor schoolbag load and posture-related information.',
          '1.2 The SmartPack platform may include hardware devices, mobile applications, dashboards, and supporting software services.',
          '1.3 Features and services available to you may depend on the SmartPack device assigned to your account and the configuration of the platform.',
        ],
      },
      {
        title: '2. ACCOUNT & ACCESS',
        paragraphs: [
          '2.1 You must maintain an active SmartPack account to access features that require authentication.',
          '2.2 You are responsible for keeping your account credentials secure and for activity performed through your account.',
          '2.3 You must provide accurate information when creating or updating your account.',
          '2.4 SmartPack may restrict or suspend access where necessary to protect the platform, its users, or devices from misuse.',
        ],
      },
      {
        title: '3. SMARTPACK DEVICES',
        paragraphs: [
          '3.1 SmartPack devices must be used only for their intended purpose and in accordance with the provided instructions.',
          '3.2 You must not intentionally damage, modify, dismantle, or tamper with SmartPack hardware or its sensors.',
          '3.3 Device functionality may depend on battery power, connectivity, hardware condition, and other environmental factors.',
          '3.4 SmartPack may require a device to be serviced, replaced, or updated to maintain proper functionality.',
        ],
      },
      {
        title: '4. DATA & PRIVACY',
        paragraphs: [
          '4.1 SmartPack may collect information required to provide its services, including account information and data generated by connected SmartPack devices.',
          '4.2 Information collected through the platform is used to provide monitoring, notifications, analytics, device management, and related services.',
          '4.3 You should only provide information that you are authorized to provide and should use the platform in accordance with applicable privacy and data protection requirements.',
          '4.4 SmartPack will take reasonable measures to protect information processed through its services.',
        ],
      },
      {
        title: '5. SERVICE AVAILABILITY',
        paragraphs: [
          '5.1 SmartPack services may depend on internet connectivity, mobile devices, power, hardware, and other third-party infrastructure.',
          '5.2 SmartPack does not guarantee uninterrupted availability of all services or features.',
          '5.3 Temporary interruptions may occur because of maintenance, updates, connectivity issues, hardware problems, or circumstances outside SmartPack’s reasonable control.',
        ],
      },
      {
        title: '6. ACCEPTABLE USE',
        paragraphs: [
          '6.1 You agree to use SmartPack services only for lawful and intended purposes.',
          '6.2 You must not attempt to gain unauthorized access to SmartPack accounts, devices, systems, or data.',
          '6.3 You must not interfere with the operation or security of the SmartPack platform.',
          '6.4 You must not use SmartPack services in a manner that could harm other users, devices, or the platform.',
        ],
      },
      {
        title: '7. CHANGES TO TERMS',
        paragraphs: [
          '7.1 These Terms and Conditions may be updated as the SmartPack platform and services develop.',
          '7.2 Where appropriate, users will be notified of material changes through the application, dashboard, email, or another available communication channel.',
          '7.3 Continued use of SmartPack services after an updated version becomes effective constitutes acceptance of the updated terms.',
        ],
      },
    ]

    /**
     * Emit a confirmation indicating the user accepted the terms.
     */
    const confirmAgreement = () => {
      emit('confirmed', true)
    }

    /**
     * Emit a decline so consumers can cancel the modal flow.
     */
    const cancelAgreement = () => {
      emit('confirmed', false)
    }

    return {
      confirmAgreement,
      cancelAgreement,
      sections,
    }
  },
})
</script>
